apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
stringData:
  secret.yaml: |

    # 数据库
    db_host: {{ .Values.depServices.rds.host | quote }}
    db_port: {{ .Values.depServices.rds.port }}
    user_name: {{ .Values.depServices.rds.user | quote }}
    user_pwd: {{ .Values.depServices.rds.password | quote }}
    db_name: {{ .Values.depServices.rds.database | quote }}
    db_charset: {{ .Values.depServices.rds.dbCharset | quote }}

    #redis服务
    redis:
      connectInfo:
        username: {{.Values.depServices.redis.connectInfo.username | quote }}
        password: {{.Values.depServices.redis.connectInfo.password | quote }}
        sentinelUsername: {{.Values.depServices.redis.connectInfo.sentinelUsername | quote }}
        sentinelPassword: {{.Values.depServices.redis.connectInfo.sentinelPassword | quote }}
