-- Migration generated by the command below; DO NOT EDIT.
-- hydra:generate hydra migrate gen
use hydra_v2;

CREATE TABLE IF NOT EXISTS `networks` (
  `id` char(36) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_client` (
  `id` varchar(255) NOT NULL,
  `client_name` text NOT NULL,
  `client_secret` text NOT NULL,
  `scope` text NOT NULL,
  `owner` text NOT NULL,
  `policy_uri` text NOT NULL,
  `tos_uri` text NOT NULL,
  `client_uri` text NOT NULL,
  `logo_uri` text NOT NULL,
  `client_secret_expires_at` int NOT NULL DEFAULT '0',
  `sector_identifier_uri` text NOT NULL,
  `jwks` text NOT NULL,
  `jwks_uri` text NOT NULL,
  `token_endpoint_auth_method` varchar(25) NOT NULL DEFAULT '',
  `request_object_signing_alg` varchar(10) NOT NULL DEFAULT '',
  `userinfo_signed_response_alg` varchar(10) NOT NULL DEFAULT '',
  `subject_type` varchar(15) NOT NULL DEFAULT '',
  `pk_deprecated` int unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `frontchannel_logout_uri` text NOT NULL,
  `frontchannel_logout_session_required` boolean NOT NULL DEFAULT '0',
  `backchannel_logout_uri` text NOT NULL,
  `backchannel_logout_session_required` boolean NOT NULL DEFAULT '0',
  `metadata` text NOT NULL,
  `token_endpoint_auth_signing_alg` varchar(10) NOT NULL DEFAULT '',
  `authorization_code_grant_access_token_lifespan` bigint DEFAULT NULL,
  `authorization_code_grant_id_token_lifespan` bigint DEFAULT NULL,
  `authorization_code_grant_refresh_token_lifespan` bigint DEFAULT NULL,
  `client_credentials_grant_access_token_lifespan` bigint DEFAULT NULL,
  `implicit_grant_access_token_lifespan` bigint DEFAULT NULL,
  `implicit_grant_id_token_lifespan` bigint DEFAULT NULL,
  `jwt_bearer_grant_access_token_lifespan` bigint DEFAULT NULL,
  `password_grant_access_token_lifespan` bigint DEFAULT NULL,
  `password_grant_refresh_token_lifespan` bigint DEFAULT NULL,
  `refresh_token_grant_id_token_lifespan` bigint DEFAULT NULL,
  `refresh_token_grant_access_token_lifespan` bigint DEFAULT NULL,
  `refresh_token_grant_refresh_token_lifespan` bigint DEFAULT NULL,
  `pk` char(36) NOT NULL,
  `registration_access_token_signature` varchar(128) NOT NULL DEFAULT '',
  `nid` char(36) NOT NULL,
  `redirect_uris` json NOT NULL,
  `grant_types` json NOT NULL,
  `response_types` json NOT NULL,
  `audience` json NOT NULL,
  `allowed_cors_origins` json NOT NULL,
  `contacts` json NOT NULL,
  `request_uris` json NOT NULL,
  `post_logout_redirect_uris` json NOT NULL,
  `access_token_strategy` varchar(10) NOT NULL DEFAULT '',
  `skip_consent` boolean NOT NULL DEFAULT '0',
  PRIMARY KEY (`pk`),
  UNIQUE KEY `hydra_client_id_key` (`id`,`nid`),
  KEY `pk_deprecated` (`pk_deprecated`),
  KEY `hydra_client_nid_fk_idx` (`nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_jwk` (
  `sid` varchar(255) NOT NULL,
  `kid` varchar(255) NOT NULL,
  `version` int NOT NULL DEFAULT '0',
  `keydata` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pk_deprecated` int unsigned NOT NULL AUTO_INCREMENT,
  `pk` char(36) NOT NULL,
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`pk`),
  UNIQUE KEY `hydra_jwk_sid_kid_nid_key` (`sid`,`kid`,`nid`),
  KEY `pk_deprecated` (`pk_deprecated`),
  KEY `hydra_jwk_nid_fk_idx` (`nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_authentication_session` (
  `id` varchar(40) NOT NULL,
  `authenticated_at` timestamp NULL DEFAULT NULL,
  `subject` varchar(255) NOT NULL,
  `remember` boolean NOT NULL DEFAULT '0',
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `hydra_oauth2_authentication_session_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_authentication_session_subject_nid_idx` (`subject`,`nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_flow` (
  `login_challenge` varchar(40) NOT NULL,
  `login_verifier` varchar(40) NOT NULL,
  `login_csrf` varchar(40) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `request_url` text NOT NULL,
  `login_skip` boolean NOT NULL,
  `client_id` varchar(255) NOT NULL,
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `login_initialized_at` timestamp NULL DEFAULT NULL,
  `oidc_context` json NOT NULL,
  `login_session_id` varchar(40),
  `state` smallint NOT NULL,
  `login_remember` boolean NOT NULL DEFAULT '0',
  `login_remember_for` int NOT NULL,
  `login_error` text,
  `acr` text NOT NULL,
  `login_authenticated_at` timestamp NULL DEFAULT NULL,
  `login_was_used` boolean NOT NULL DEFAULT '0',
  `forced_subject_identifier` varchar(255) NOT NULL DEFAULT '',
  `context` json NOT NULL,
  `consent_challenge_id` varchar(40) DEFAULT NULL,
  `consent_skip` boolean NOT NULL DEFAULT '0',
  `consent_verifier` varchar(40) DEFAULT NULL,
  `consent_csrf` varchar(40) DEFAULT NULL,
  `consent_remember` boolean NOT NULL DEFAULT '0',
  `consent_remember_for` int DEFAULT NULL,
  `consent_handled_at` timestamp NULL DEFAULT NULL,
  `consent_error` text,
  `session_access_token` json NOT NULL,
  `session_id_token` json NOT NULL,
  `consent_was_used` boolean DEFAULT NULL,
  `nid` char(36) NOT NULL,
  `requested_scope` json NOT NULL,
  `requested_at_audience` json DEFAULT NULL,
  `amr` json DEFAULT NULL,
  `granted_scope` json DEFAULT NULL,
  `granted_at_audience` json DEFAULT NULL,
  `login_extend_session_lifespan` boolean NOT NULL DEFAULT '0',
  PRIMARY KEY (`login_challenge`),
  UNIQUE KEY `hydra_oauth2_flow_login_verifier_idx` (`login_verifier`),
  UNIQUE KEY `hydra_oauth2_flow_consent_challenge_idx` (`consent_challenge_id`),
  UNIQUE KEY `hydra_oauth2_flow_consent_verifier_idx` (`consent_verifier`),
  KEY `hydra_oauth2_flow_login_session_id_idx` (`login_session_id`),
  KEY `hydra_oauth2_flow_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_flow_client_id_subject_idx` (`client_id`,`nid`,`subject`),
  KEY `hydra_oauth2_flow_sub_idx` (`subject`,`nid`),
  KEY `hydra_oauth2_flow_multi_query_idx` (`consent_error`(2),`state`,`subject`,`client_id`,`consent_skip`,`consent_remember`,`nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_access` (
  `signature` varchar(255) NOT NULL,
  `request_id` varchar(40) NOT NULL DEFAULT '',
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `client_id` varchar(255) NOT NULL DEFAULT '',
  `scope` text NOT NULL,
  `granted_scope` text NOT NULL,
  `form_data` text NOT NULL,
  `session_data` text NOT NULL,
  `subject` varchar(255) NOT NULL DEFAULT '',
  `active` boolean NOT NULL DEFAULT '1',
  `requested_audience` text NOT NULL,
  `granted_audience` text NOT NULL,
  `challenge_id` varchar(40) DEFAULT NULL,
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`signature`),
  KEY `hydra_oauth2_access_challenge_id_idx` (`challenge_id`),
  KEY `hydra_oauth2_access_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_access_client_id_fk` (`client_id`,`nid`),
  KEY `hydra_oauth2_access_requested_at_idx` (`requested_at`,`nid`),
  KEY `hydra_oauth2_access_client_id_subject_nid_idx` (`client_id`,`subject`,`nid`),
  KEY `hydra_oauth2_access_request_id_idx` (`request_id`,`nid`),
  CONSTRAINT `hydra_oauth2_access_challenge_id_fk` FOREIGN KEY (`challenge_id`) REFERENCES `hydra_oauth2_flow` (`consent_challenge_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_code` (
  `signature` varchar(255) NOT NULL,
  `request_id` varchar(40) NOT NULL DEFAULT '',
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `client_id` varchar(255) NOT NULL DEFAULT '',
  `scope` text NOT NULL,
  `granted_scope` text NOT NULL,
  `form_data` text NOT NULL,
  `session_data` text NOT NULL,
  `subject` varchar(255) NOT NULL DEFAULT '',
  `active` boolean NOT NULL DEFAULT '1',
  `requested_audience` text NOT NULL,
  `granted_audience` text NOT NULL,
  `challenge_id` varchar(40) DEFAULT NULL,
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`signature`),
  KEY `hydra_oauth2_code_challenge_id_idx` (`challenge_id`),
  KEY `hydra_oauth2_code_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_code_client_id_fk` (`client_id`,`nid`),
  KEY `hydra_oauth2_code_request_id_idx` (`request_id`,`nid`),
  CONSTRAINT `hydra_oauth2_code_challenge_id_fk` FOREIGN KEY (`challenge_id`) REFERENCES `hydra_oauth2_flow` (`consent_challenge_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_jti_blacklist` (
  `signature` varchar(64) NOT NULL,
  `expires_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`signature`,`nid`),
  KEY `hydra_oauth2_jti_blacklist_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_jti_blacklist_expiry` (`expires_at`,`nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_logout_request` (
  `challenge` varchar(36) NOT NULL,
  `verifier` varchar(36) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `sid` varchar(36) NOT NULL,
  `client_id` varchar(255) DEFAULT NULL,
  `request_url` text NOT NULL,
  `redir_url` text NOT NULL,
  `was_used` boolean NOT NULL DEFAULT '0',
  `accepted` boolean NOT NULL DEFAULT '0',
  `rejected` boolean NOT NULL DEFAULT '0',
  `rp_initiated` boolean NOT NULL DEFAULT '0',
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`challenge`),
  UNIQUE KEY `hydra_oauth2_logout_request_veri_idx` (`verifier`),
  KEY `hydra_oauth2_logout_request_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_logout_request_client_id_fk` (`client_id`,`nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_obfuscated_authentication_session` (
  `subject` varchar(255) NOT NULL,
  `client_id` varchar(255) NOT NULL,
  `subject_obfuscated` varchar(255) NOT NULL,
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`subject`,`client_id`,`nid`),
  UNIQUE KEY `hydra_oauth2_obfuscated_authentication_session_so_nid_idx` (`client_id`,`subject_obfuscated`,`nid`),
  KEY `hydra_oauth2_obfuscated_authentication_session_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_obfuscated_authentication_session_client_id_fk` (`client_id`,`nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_oidc` (
  `signature` varchar(255) NOT NULL,
  `request_id` varchar(40) NOT NULL DEFAULT '',
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `client_id` varchar(255) NOT NULL DEFAULT '',
  `scope` text NOT NULL,
  `granted_scope` text NOT NULL,
  `form_data` text NOT NULL,
  `session_data` text NOT NULL,
  `subject` varchar(255) NOT NULL DEFAULT '',
  `active` boolean NOT NULL DEFAULT '1',
  `requested_audience` text NOT NULL,
  `granted_audience` text NOT NULL,
  `challenge_id` varchar(40) DEFAULT NULL,
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`signature`),
  KEY `hydra_oauth2_oidc_challenge_id_idx` (`challenge_id`),
  KEY `hydra_oauth2_oidc_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_oidc_client_id_fk` (`client_id`,`nid`),
  KEY `hydra_oauth2_oidc_request_id_idx` (`request_id`,`nid`),
  CONSTRAINT `hydra_oauth2_oidc_challenge_id_fk` FOREIGN KEY (`challenge_id`) REFERENCES `hydra_oauth2_flow` (`consent_challenge_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_pkce` (
  `signature` varchar(255) NOT NULL,
  `request_id` varchar(40) NOT NULL DEFAULT '',
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `client_id` varchar(255) NOT NULL DEFAULT '',
  `scope` text NOT NULL,
  `granted_scope` text NOT NULL,
  `form_data` text NOT NULL,
  `session_data` text NOT NULL,
  `subject` varchar(255) NOT NULL,
  `active` boolean NOT NULL DEFAULT '1',
  `requested_audience` text NOT NULL,
  `granted_audience` text NOT NULL,
  `challenge_id` varchar(40) DEFAULT NULL,
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`signature`),
  KEY `hydra_oauth2_pkce_challenge_id_idx` (`challenge_id`),
  KEY `hydra_oauth2_pkce_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_pkce_client_id_fk` (`client_id`,`nid`),
  KEY `hydra_oauth2_pkce_request_id_idx` (`request_id`,`nid`),
  CONSTRAINT `hydra_oauth2_pkce_challenge_id_fk` FOREIGN KEY (`challenge_id`) REFERENCES `hydra_oauth2_flow` (`consent_challenge_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_refresh` (
  `signature` varchar(255) NOT NULL,
  `request_id` varchar(40) NOT NULL DEFAULT '',
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `client_id` varchar(255) NOT NULL DEFAULT '',
  `scope` text NOT NULL,
  `granted_scope` text NOT NULL,
  `form_data` text NOT NULL,
  `session_data` text NOT NULL,
  `subject` varchar(255) NOT NULL DEFAULT '',
  `active` boolean NOT NULL DEFAULT '1',
  `requested_audience` text NOT NULL,
  `granted_audience` text NOT NULL,
  `challenge_id` varchar(40) DEFAULT NULL,
  `nid` char(36) NOT NULL,
  PRIMARY KEY (`signature`),
  KEY `hydra_oauth2_refresh_challenge_id_idx` (`challenge_id`),
  KEY `hydra_oauth2_refresh_client_id_fk` (`client_id`,`nid`),
  KEY `hydra_oauth2_refresh_client_id_subject_idx` (`client_id`,`subject`),
  KEY `hydra_oauth2_refresh_request_id_idx` (`request_id`),
  KEY `hydra_oauth2_refresh_requested_at_idx` (`nid`,`requested_at`),
  CONSTRAINT `hydra_oauth2_refresh_challenge_id_fk` FOREIGN KEY (`challenge_id`) REFERENCES `hydra_oauth2_flow` (`consent_challenge_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `hydra_oauth2_trusted_jwt_bearer_issuer` (
  `id` varchar(36) NOT NULL,
  `issuer` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `scope` text NOT NULL,
  `key_set` varchar(255) NOT NULL,
  `key_id` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nid` char(36) NOT NULL,
  `allow_any_subject` boolean NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `issuer` (`issuer`,`subject`,`key_id`),
  KEY `hydra_oauth2_trusted_jwt_bearer_issuer_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_trusted_jwt_bearer_issuer_ibfk_1` (`key_set`,`key_id`,`nid`),
  KEY `hydra_oauth2_trusted_jwt_bearer_issuer_expires_at_idx` (`expires_at`),
  CONSTRAINT `hydra_oauth2_trusted_jwt_bearer_issuer_ibfk_1` FOREIGN KEY (`key_set`, `key_id`, `nid`) REFERENCES `hydra_jwk` (`sid`, `kid`, `nid`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `networks`
(`id`, `created_at`, `updated_at`)
SELECT
    (SELECT LOWER(UUID())),
    '2013-10-07 08:23:19',
    '2013-10-07 08:23:19'
FROM DUAL
WHERE NOT EXISTS (SELECT `created_at` FROM `networks` WHERE `created_at` = '2013-10-07 08:23:19');
