replicaCount: 1

nodeSelector: {}

namespace: anyshare

image:
  registry: ""
  service:
    repository: as/authorization
    tag: ""
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 30920
  ginMode: release
  language: zh_CN
  logger: stdout
  sslOn: false
  certFile: /sysvol/conf/authorization.crt
  keyFile: /sysvol/conf/authorization.key
  businessTimeOffset: 0
  logLevel: info # 因为升级过程会沿用旧值, 此处改动不会生效, 所以configmap中日志等级不再引用此值
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 3
    timeoutSeconds: 3
    failureThreshold: 3
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  enableDualStack: false

env:
  language: en_US.UTF-8
  timezone: Asia/Shanghai

depServices:
  rds:
    system_id: ''
    type: mysql
    host: 127.0.0.1
    port: 3320
    driver: mysql
    user: ""
    password: ""
    database: anyshare
    maxConnections: 30
    dbCharset: utf8mb4
    timeout: 10
    readTimeout: 10
    writeTimeout: 10
  hydra:
    publicHost: hydra-public
    publicPort: 4444
    administrativeHost: hydra-admin
    administrativePort: 4445
  mq: {}
  mqConfigFilePath: /sysvol/conf/service_conf/mq_config.yaml
  user-management:
    privateHost: user-management-private
    privatePort: 30980
  redis:
    connectType: sentinel|standalone|master-slave
    enableSSL: false
    connectInfo:
      username: ""
      password: ""
      host: ""
      port: 26379
      masterHost: ""
      masterPort: 26379
      slaveHost: ""
      slavePort: 26379
      sentinelHost: proton-redis-proton-redis-sentinel.resource.svc.cluster.local
      sentinelPort: 26379
      sentinelUsername: ""
      sentinelPassword: ""
      masterGroupName: mymaster
    secretName: ""
    caName: ""
    certName: ""
    keyName: ""

securityContext:
  runAsUser: 5000
  runAsGroup: 5000

resources:
  requests:
    cpu: 19m
    memory: 100Mi
  limits:
    cpu: 16
    memory: 4Gi
