apiVersion: v1
appVersion: "1.0.0"
description: A Helm authentication service chart for Kubernetes
name: authentication
version: 1.0.0
keywords:
  - authentication
  - InformationSecurityFabric
engine: gotpl
